### ISSUE TITLE
Decouple Obsidian

### ISSUE THREAD

**Issue by Seb-stian** [ObsidianMC/Obsidian#185]
Obsidian is a large project that consists of many parts. At the moment, everything sort of melts together, which is bad for maintainability and extensibility.

- [x] Separate console front-end to a new project
  - [x] Make sure that we only have things `public` when they should be
  - [x] Make types `sealed` as appropriate
- [x] Move `Obsidian.ConversionUtility` to repository `Tools`
- [x] Move `Obsidian/scripts` to repository `Tools`
- [x] Move `Obsidian.Nbt` to its own repository
- [ ] Rethink project folder/namespace structure (?)

Some tasks (?) need further discussing.

**Comment by vix127** [comment]
Shouldn't `Move Obsidian.Nbt to its own repository` be checked?
